# Site settings
title: Robert Herbig
email: robert@rpherbig.com
description: >
  I try to improve myself and those around me every day.
baseurl: ""
url: "http://www.rpherbig.com"
twitter_username: rpherbig
github_username:  rpherbig

# Build settings
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap
